# Generated by Django 5.0.1 on 2024-02-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_alter_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('to-do', 'To-Do'), ('in progress', 'In Progress'), ('finished', 'Finished')], default='To Do', max_length=50),
        ),
    ]
